### ISSUE TITLE
Cone/Gate key focus

### ISSUE THREAD

**Issue by drytoastman** [drytoastman/wwscc#51]
Key listening only works when the time entry area has focus.  If a user clicks on a run field and then a time comes in, the time textfield gets the new data but c/g keys don't work.  Need to catch keys on the table and time JList and send them along.

**Comment by dpodhola** [comment]
If you press "Enter/Return" while the table is selected, does it enter the time or do you have to have to the time-form focused?

**Comment by drytoastman** [comment]
I was just checking that out.  The table specifically catches Enter and sends an event to the timeentry.  I'm fixing that now.  Also registered a key listener with the JList incase someone clicks the same time a second time as focus sticks there.

**Comment by dpodhola** [comment]
IMO, if I was the user and I had the table-part of the UI selected and I pressed c/g, I'd expect it to modify what I was actively working on, not the time box I wasn't focusing on.

**Comment by drytoastman** [comment]
True.  We had a similar problem before where a new time coming in would take focus from entering a new driver.

In this case, you can't actually type into a table entry directly.  I was thinking of forwarding c/g keys when a blank run is selected as the user is thinking about entering time from the right into the box.
